name: Playwright Tests
on:
  pull_request:
    branches: main
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - firefox
          - chromium
          - webkit

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clone app repo
      env:
        PAT: ${{ secrets.APP_REPO_PAT }}
      run: git clone https://$PAT@github.com/OrchidSoleil/gwara-project.git app
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'     # Set this to your Django app's Python version
    - name: Install dependencies
      run: npm ci
    - name: Install app dependencies
      run: cd app && npm ci || true   # in case there is no package.json in app, don't fail
    - name: Install Django dependencies
      run: cd app && pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > app/.env
        echo "DATABASE=${{ secrets.DATABASE }}" >> app/.env
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> app/.env
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> app/.env
        echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> app/.env
        echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> app/.env
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> app/.env
        echo "FLUSH=${{ secrets.FLUSH }}" >> app/.env
        echo "FLUSH_CODE=${{ secrets.FLUSH_CODE }}" >> app/.env
    - name: Start app
      run: cd app && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 & sleep 10
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --project ${{ github.event.inputs.browser }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30